# Generated by Django 5.1.1 on 2024-11-23 06:48

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='company_logos/default.png', upload_to='company_logos')),
                ('employer_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('state_or_province', models.CharField(max_length=200)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('zip_code', models.CharField(max_length=50)),
                ('about_employer', models.TextField()),
                ('website', models.URLField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('representative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employer_name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('marketing & advertising', 'Marketing & Advertising'), ('engineering', 'Engineering'), ('manufacturing', 'Manufacturing'), ('retail & sales', 'Retail & Sales'), ('hospitality', 'Hospitality'), ('construction', 'Construction'), ('telecommunications', 'Telecommunications'), ('real estate', 'Real Estate'), ('nonprofit', 'Nonprofit'), ('food and beverage', 'Food and Beverage'), ('government', 'Government'), ('arts & entertainment', 'Arts & Entertainment'), ('other', 'Other')], max_length=100)),
                ('job_title', models.CharField(max_length=200)),
                ('job_type', models.CharField(blank=True, choices=[('full time', 'Full Time'), ('part time', 'Part Time'), ('contract', 'Contract')], max_length=100, null=True)),
                ('experience_level', models.CharField(blank=True, choices=[('no experience', 'No Experience'), ('1 to 2 years', '1 to 2 years'), ('3 to 4 years', '3 to 4 years'), ('5 to 6 years', '5 to 6 years'), ('7 years or more', '7 years or more')], max_length=100, null=True)),
                ('work_location', models.CharField(blank=True, choices=[('remote', 'Remote'), ('on site', 'On Site'), ('hybrid', 'Hybrid')], max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=100)),
                ('qualification', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('applicants', models.ManyToManyField(blank=True, to='candidates.candidatequalification')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='employers.employer')),
            ],
        ),
    ]
