# Generated by Django 5.1.1 on 2024-12-02 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='zip_code',
            new_name='zip_code_or_postal_code',
        ),
    ]
