# Generated by Django 5.1.1 on 2024-10-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='description',
            field=models.TextField(default='set null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='website',
            field=models.URLField(default='set null', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos'),
        ),
    ]
