# Generated by Django 5.1.1 on 2024-10-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='employer',
            name='slug',
            field=models.SlugField(default='None', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='logo',
            field=models.ImageField(blank=True, default='company_logos/default.png', null=True, upload_to='company_logos'),
        ),
    ]
