# Generated by Django 5.1.1 on 2024-12-02 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_phone_number'),
        ('employers', '0002_rename_zip_code_employer_zip_code_or_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='representative',
        ),
        migrations.AddField(
            model_name='employer',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile'),
        ),
    ]
