# Generated by Django 5.1.1 on 2024-10-12 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_employer_description_employer_website_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['company']},
        ),
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
    ]
