# Generated by Django 5.1.1 on 2024-10-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_job_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
