# Generated by Django 5.1.1 on 2024-10-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_alter_job_options_remove_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=models.TextField(default='set null'),
            preserve_default=False,
        ),
    ]
