# Generated by Django 5.1.1 on 2024-12-02 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_phone_number'),
        ('employers', '0003_remove_employer_representative_employer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile'),
        ),
    ]
