# Generated by Django 5.1.1 on 2024-10-23 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0004_alter_job_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={'ordering': ['company_name']},
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='company',
            new_name='company_name',
        ),
    ]
