# Generated by Django 5.1.1 on 2024-12-02 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_phone_number'),
        ('employers', '0004_alter_employer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employers', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='website',
            field=models.URLField(blank=True, help_text='Website address must start with https:// follow by www.company.com', max_length=300, null=True),
        ),
    ]
