# Generated by Django 5.1.1 on 2024-10-23 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0005_alter_employer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={'ordering': ['employer_name']},
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='company_name',
            new_name='employer_name',
        ),
    ]
