# Generated by Django 5.1.1 on 2024-12-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0005_alter_employer_profile_alter_employer_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('no experience', 'No Experience'), ('1 to 2 years', '1 to 2 years'), ('3 to 4 years', '3 to 4 years'), ('5 to 6 years', '5 to 6 years'), ('7 years or more', '7 years or more')], default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full time', 'Full Time'), ('part time', 'Part Time'), ('contract', 'Contract')], default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='work_location',
            field=models.CharField(choices=[('remote', 'Remote'), ('on site', 'On Site'), ('hybrid', 'Hybrid')], default='none', max_length=100),
            preserve_default=False,
        ),
    ]
