# Generated by Django 5.1.1 on 2024-12-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0006_alter_job_experience_level_alter_job_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.TextField(default=2600),
        ),
    ]
