# Generated by Django 5.1.1 on 2024-10-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0006_alter_employer_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='description',
            new_name='about_employer',
        ),
    ]
