# Generated by Django 5.1.1 on 2024-12-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0007_alter_job_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.TextField(),
        ),
    ]
