# Generated by Django 5.1.1 on 2024-10-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0007_rename_description_employer_about_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='logo',
            field=models.ImageField(default='company_logos/default.png', upload_to='company_logos'),
        ),
    ]
