# Generated by Django 5.1.1 on 2024-10-23 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0008_alter_employer_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='company',
            new_name='employer',
        ),
    ]
