# Generated by Django 5.1.1 on 2024-12-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0008_alter_job_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_description',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
