# Generated by Django 5.1.1 on 2024-10-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0009_rename_company_job_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='city',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='state_or_province',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
