# Generated by Django 5.1.1 on 2024-12-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0009_job_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='payment_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('monthly', 'Monthly')], default='none', max_length=50),
            preserve_default=False,
        ),
    ]
