# Generated by Django 5.1.1 on 2024-12-05 21:53

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0010_job_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='currency',
            field=django_countries.fields.CountryField(default='none', max_length=2),
            preserve_default=False,
        ),
    ]
