# Generated by Django 5.1.1 on 2024-10-24 05:31

import django.utils.timezone
import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0010_employer_city_employer_state_or_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='country',
            field=django_countries.fields.CountryField(default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
