# Generated by Django 5.1.1 on 2024-10-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidate_slug'),
        ('employers', '0011_employer_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applicants',
            field=models.ManyToManyField(blank=True, to='candidates.candidate'),
        ),
    ]
