# Generated by Django 5.1.1 on 2024-12-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0012_job_currency_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='payment_type',
            field=models.CharField(choices=[('hour', 'Hourly'), ('month', 'Monthly')], max_length=50),
        ),
    ]
