# Generated by Django 5.1.1 on 2024-10-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['company'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['category']},
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
    ]
