# Generated by Django 5.1.1 on 2024-10-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
    ]
