# Generated by Django 5.1.1 on 2024-11-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Max digits 15, must start with + follow by country code.', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='portfolio_or_personal_website',
            field=models.URLField(blank=True, help_text='Must start with https://', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_link',
            field=models.URLField(blank=True, help_text='Must start with https://', null=True),
        ),
    ]
