# Generated by Django 5.1.1 on 2024-10-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_avatar_profile_profile_image_and_more'),
        ('candidates', '0011_alter_industry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_profiles',
            field=models.ManyToManyField(to='candidates.candidatejobprofile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='profile_images/default.png', upload_to='profile_images'),
        ),
    ]
