# Generated by Django 5.1.1 on 2024-10-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_job_profiles_alter_profile_profile_image'),
        ('candidates', '0012_remove_industry_candidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='job_profiles',
            field=models.ManyToManyField(blank=True, to='candidates.candidatejobprofile'),
        ),
    ]
