# Generated by Django 5.1.1 on 2024-12-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Max digits 15, must start with + follow by country code.', max_length=15, null=True),
        ),
    ]
