# Generated by Django 5.1.1 on 2024-12-04 21:41

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_post_code_or_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default=2600, max_length=2),
        ),
    ]
