# Generated by Django 5.1.1 on 2024-12-04 21:42

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='post_code_or_zip_code',
            field=models.CharField(blank=True, default='2600', max_length=50, null=True),
        ),
    ]
