# Generated by Django 5.1.1 on 2024-12-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='post_code_or_zip_code',
            field=models.CharField(default='2600', max_length=50),
        ),
    ]
