# Generated by Django 5.1.1 on 2024-12-06 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_post_code_or_zip_code'),
        ('employers', '0013_alter_job_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('applied_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employers.job')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_jobs', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='accounts.profile')),
                ('saved_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employers.job')),
            ],
        ),
    ]
