# Generated by Django 5.1.1 on 2025-02-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_profile_portfolio_or_personal_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='none', max_length=15),
            preserve_default=False,
        ),
    ]
