# Generated by Django 5.1.1 on 2024-11-16 05:54

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Industries',
            },
        ),
        migrations.CreateModel(
            name='CandidateJobProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('marketing & advertising', 'Marketing & Advertising'), ('engineering', 'Engineering'), ('manufacturing', 'Manufacturing'), ('retail & sales', 'Retail & Sales'), ('hospitality', 'Hospitality'), ('construction', 'Construction'), ('telecommunications', 'Telecommunications'), ('real estate', 'Real Estate'), ('nonprofit', 'Nonprofit'), ('food and beverage', 'Food and Beverage'), ('government', 'Government'), ('arts & entertainment', 'Arts & Entertainment'), ('other', 'Other')], max_length=200)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state_or_province', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('job_title', models.CharField(max_length=200)),
                ('skills', models.CharField(blank=True, max_length=300, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes')),
                ('social_link', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Candidate Job Profiles',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
    ]
