# Generated by Django 5.1.1 on 2024-10-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='avatar',
            field=models.ImageField(default='candidate_avatars/default.png', upload_to='candidate_avatars'),
        ),
    ]
