# Generated by Django 5.1.1 on 2024-10-15 09:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_remove_job_company_remove_job_applicants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobSeeker',
            new_name='Candidate',
        ),
    ]
