# Generated by Django 5.1.1 on 2024-10-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_candidate_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='slug',
            field=models.SlugField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
