# Generated by Django 5.1.1 on 2024-11-23 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('candidates', '0002_alter_candidatequalification_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatequalification',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
