# Generated by Django 5.1.1 on 2024-11-25 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_alter_candidatequalification_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date']},
        ),
    ]
