# Generated by Django 5.1.1 on 2024-10-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_rename_jobseeker_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='occupation',
        ),
        migrations.AddField(
            model_name='candidate',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes'),
        ),
    ]
