# Generated by Django 5.1.1 on 2024-10-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_alter_candidate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='social_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
