# Generated by Django 5.1.1 on 2024-11-26 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_alter_education_options_alter_experience_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='candidates.candidatequalification'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='candidates.candidatequalification'),
        ),
    ]
