# Generated by Django 5.1.1 on 2024-10-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_remove_candidate_occupation_candidate_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='social_link',
            field=models.URLField(default='None'),
            preserve_default=False,
        ),
    ]
