# Generated by Django 5.1.1 on 2024-11-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_alter_education_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
