# Generated by Django 5.1.1 on 2024-10-27 19:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_alter_candidate_user'),
        ('employers', '0012_alter_job_applicants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Candidate',
            new_name='CandidateJobProfile',
        ),
    ]
