# Generated by Django 5.1.1 on 2024-10-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_rename_candidate_candidatejobprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatejobprofile',
            options={'verbose_name_plural': 'Candidate Job Profiles'},
        ),
        migrations.AddField(
            model_name='candidatejobprofile',
            name='skills',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
