# Generated by Django 5.1.1 on 2024-10-27 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_alter_candidatejobprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatejobprofile',
            name='avatar',
        ),
    ]
