# Generated by Django 5.1.1 on 2024-10-28 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_industry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name_plural': 'Industries'},
        ),
    ]
