# Generated by Django 5.1.1 on 2024-10-28 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0011_alter_industry_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industry',
            name='candidate',
        ),
        migrations.AddField(
            model_name='candidatejobprofile',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.industry'),
        ),
    ]
